### ISSUE TITLE
Option for runner to register with a specific job tag

### ISSUE THREAD

**Issue by sammcj** [woodjme/autoscaling-ec2-gitlab-runners-fargate#1]
**Is your feature request related to a problem? Please describe.**

It would be great if you could optionally pass in the tag(s) the runner to register with in the stack configuration.

Detail:

In GitLab CI you can configure runners (or coordinators in this case) with a tag(s) so that they only pick-up CI jobs with that tag(s), see 
https://docs.gitlab.com/ee/ci/runners/#using-tags and https://docs.gitlab.com/ee/ci/yaml/README.html#tags

This is extremely useful for separating stages that may need to run in or deploy to different environments.

For example you might have separate runners deployed in your pre-prod and prod environments, production deployments might be run by a stage with a tag that only production agents pick-up.

When registering a runner manually you specify the specific tags during `gitlab-runner register` process:

```
# Please enter the gitlab-ci tags for this runner (comma separated):
my-tag,another-tag
```

**Describe the solution you'd like**

I started to look into this and I can see it might be a bit of a pain as the register command that would need the tag is baked into the container image, maybe it could be read from an environment variable?

--

_also thank you for taking the time to share your pattern for this!_

**Comment by sammcj** [comment]
Fixed in https://github.com/woodjme/autoscaling-ec2-gitlab-runners-fargate/pull/3 which allows passing `gitlab-runner register` additional parameters such as `--tag-list mytag`

**Comment by woodjme** [comment]
Using `$RUNNER_TAG_LIST` environment variable passed through from the CloudFormation template is a nicer way of doing the tags specifically, but, I do like the concept in #3 of allowing users to 'bring their own' params.

**Comment by woodjme** [comment]
Leaving this open until `$RUNNER_TAG_LIST` has been implemented
