### ISSUE TITLE
Docker daemon port exposed to the internet by default

### ISSUE THREAD

**Issue by sammcj** [woodjme/autoscaling-ec2-gitlab-runners-fargate#2]
**Describe the bug**

By default when using this CloudFormation template the security group that is created (docker-machine) exposes Docker's daemon port (TCP/2376) to the internet (0.0.0.0/0). 

This is a security risk and Docker recommends that access to this port should be restricted.

https://docs.docker.com/engine/security/https/

**To Reproduce**
Steps to reproduce the behaviour:
1. Provision the CF template as a stack.
2. Navigate to security groups in the AWS console.
3. Select the docker-machine security group.
4. On the inbound tab note that TCP/2376 is exposed to 0.0.0.0/0 (the internet).

**Expected behaviour**

During the creation of the stack from the template you could be prompted to enter the subnets and IPs that should be allowed to access the runners, this could then be taken to properly configure the security group.

**Screenshots**

![screenshot 2020-02-18 at 1 55 50 pm](https://user-images.githubusercontent.com/862951/74699996-69910c00-5256-11ea-84cb-47a2af8422d0.jpg)

`nmap -Pn -p 22,2376 <ip of runner>`

```
PORT     STATE SERVICE
22/tcp   open  ssh
2376/tcp open  docker
```

**Additional context**

- https://medium.com/@logicbomb_1/hacking-docker-the-shodan-way-18c5ede1cb23
- https://blog.trendmicro.com/trendlabs-security-intelligence/misconfigured-container-abused-to-deliver-cryptocurrency-mining-malware/
- https://securityboulevard.com/2019/02/abusing-docker-api-socket/

**Comment by sammcj** [comment]
I think I just found out why this doesn't already exist in the CF - I've see that it's docker-machine creates the security group.

As far as I can tell docker-machine doesn't seem to allow for any other [settings](https://docs.docker.com/v17.09/machine/drivers/aws/#options) on the security group other than `--amazonec2-private-address-only` (which would limit people to only ever running agents in the same VPC (or via a VPN to the VPC) as the coordinator).

Perhaps the best option for now is to add a note stating that once the stack is provisioned, you should edit the `docker-machine` security group and restrict inbound access to TCP/2376 to only trusted CIDRs/IPs?

**Comment by sammcj** [comment]
Added a note recommending locking down the security group in the readme to https://github.com/woodjme/autoscaling-ec2-gitlab-runners-fargate/pull/3

**Comment by woodjme** [comment]
Hey @sammcj thanks for spotting this! 

Adding `--amazonec2-private-address-only` is going to be quite limiting for some use cases as it will stop the machine from being able to connect to the internet and therefore download public images. I understand it's best practise to use NAT Gateways in private subnets but that's perhaps a little bit out the scope of this project. 

I've found an updated list of settings [here](https://github.com/docker/docker.github.io/blob/master/machine/drivers/aws.md) which has a security group option. This would potentially allow us to create a security group with Cloudformation that only allows traffic on port `2375` from Fargate which would be more flexible.

**Comment by woodjme** [comment]
There is also a `--amazonec2-use-private-address` which looks interesting, needs to dig into exactly what it does...

**Comment by sammcj** [comment]
Thanks for merging my somewhat-related MR @woodjme!

I think if a disclaimer is added to the readme to warn / advise people this can be closed.
