### ISSUE TITLE
Restrict AmazonEC2FullAccess

### ISSUE THREAD

**Issue by sammcj** [woodjme/autoscaling-ec2-gitlab-runners-fargate#7]
**Is your feature request related to a problem? Please describe.**

- Currently AmazonEC2FullAccess is granted to the role so that EC2 runners can be spun up and deleted.
- FullAccess is overly permissive and potentially dangerous.

**Describe the solution you'd like**

- Only allow access to EC2 instances with a certain tag (`ec2:ResourceTag`).

**Additional context**

https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html

**Comment by woodjme** [comment]
#5

**Comment by sammcj** [comment]
Oh! Sorry for the dupe :)
